### PR TITLE
/croissant -> /croissant-crumbs (only specific fields)

### LINKED ISSUE #2624: remove fields from croissant once it's provided by the Hub API
Once the Hub provides an API to access the croissant metadata (https://github.com/huggingface/moon-landing/pull/9106, internal), we will be able to remove the following fields from the croissant response:
- `name`
- `description`
- `license`
- `url`

Also: we could provide `identifier` (DOI) from the Hub API, and remove it here.

Finally: it might be better to rename the datasets server endpoint /croissant-fragment, or something that indicates that it's a partial answer, not the full specification. The endpoint will only provide:
```json
{
  "@context": context,
  "@type": "sc:Dataset",
  "conformsTo": "http://mlcommons.org/croissant/1.0",
  "distribution": distribution,
  "recordSet": record_set
}
```

### PR DESCRIPTION
**Pull request by severo**
fixes #2624

### CODE REVIEW

**Comment by severo** [comment]
see also https://github.com/huggingface/datasets-server/pull/2642

**Comment by severo** [comment]
fyi @marcenacp @ccl-core

**Comment by lhoestq** [comment]
Maybe keep the bare minimum to still have a valid croissant file ?

**Comment by severo** [comment]
> Maybe keep the bare minimum to still have a valid croissant file ?

Hmmm, I don't think so. I even wanted to rename it /croissant-fragment or /partial-croissant to be crystal clear that it's not a complete croissant file. We don't want people to use this endpoint, but the one on the Hub.

**Comment by severo** [comment]
Or keep the required fields (I have to check which are), and in description, put clearly that the other endpoint should be used.

**Comment by julien-c** [comment]
IMO it's simpler if it's not a valid croissant but only a (mostly internal) "parts of croissant" (croissant-crumbs?)

**Comment by severo** [comment]
funny. Let's do that: /croissant-crumbs in parallel to /croissant, then I'll change in moon-landing, and remove /croissant here

**Comment by severo** [comment]
I rebased on your PR https://github.com/huggingface/datasets-server/pull/2642 @lhoestq.

**Review by lhoestq — APPROVED** [review]

**Pull request merged**
