### PR TITLE
Always verify parquet before copying

### PR DESCRIPTION
**Pull request by lhoestq**
close https://github.com/huggingface/datasets-server/issues/1519

### CODE REVIEW

**Comment by lhoestq** [comment]
https://github.com/huggingface/datasets-server/pull/1525 should fix the CI (and maybe there's a token to be refreshed)

**Review by severo — APPROVED** [review]

**Comment by severo** [comment]
which datasets should we recompute after that? Is there a way to know?

**Comment by lhoestq** [comment]
I don't think there's a way to know except with /rows that can detect too big row groups, maybe we can refresh the dataset when /rows detects it

**Comment by severo** [comment]
> maybe we can refresh the dataset when /rows detects it
Could be, but instead of complicating the code for that, maybe do a one-time analysis on all the datasets that have a size over ...GB

**Pull request merged**
