### PR TITLE
Give insights to the user when we raise TooBigRows

### LINKED ISSUE #2139: Give insights to the user when we raise TooBigRows in /rows, /search, or /filter
https://huggingface.co/datasets/danielz01/xView2/discussions/2#655dc3ccde919d41622b51bd

Currently, we only show

```
Error code:   UnexpectedApiError
```

We should say that the rows contents are too heavy and that we don't show them for that reason (> 400MB in that case)

### PR DESCRIPTION
**Pull request by albertvillanova**
Fix #2139.

### CODE REVIEW

**Comment by albertvillanova** [comment]
@severo thanks for your review.

> Can it also be raised in search/ and filter/?

The `TooBigRows` error (maybe we should rename it to `TooBigRowsError`) is raised by `ParquetIndexWithMetadata.query` and this is only used by:
- services/rows
- services/worker::job_runners.split.first_rows_from_parquet

The "search" and "filter" services use the DuckDB instead.

> Should we simply make TooBigRows inherit from ApiError? Or should we instead catch it in these other services?

I spent some time thinking about this but did not get a clear solution:
- The `TooBigRows` error is defined and raised by "parquet_utils", a module in "libs/libcommon", so it does not make sense that it raises an `ApiError` (defined in "libs/libapi")
- We might move the module "parquet_utils" to "libs/libapi", but the we are forced to make "services/worker" (that also uses "parquet_utils") to depned on "libs/libapi" (with all the other dependencies that are not needed by this worker)

**Comment by severo** [comment]
OK, thanks for explaining. It makes me wonder: it's somewhat incoherent not to check the same on filter and search, no? we could end up sending >500MB in one response on these endpoints?

**Comment by albertvillanova** [comment]
Yes, I thought the same, but we should first find out how to check that when reading from DuckDB file (or before writing the DuckDB file?).

Maybe open a different issue and rename the one associated with this PR?

**Comment by severo** [comment]
yes, sounds perfect

**Review by severo — APPROVED** [review]

**Pull request merged**
