### PR TITLE
Don't create empty images in /rows

### PR DESCRIPTION
**Pull request by lhoestq**
Don't create empty images. Otherwise on a second call to /rows it will return the first empty image.
We were already doing something similar for audio.

Fix https://github.com/huggingface/datasets-server/issues/2297

TODO after merged:
- [ ] delete the cached assets for HuggingFaceM4/WebSight to remove the empty images

### CODE REVIEW

**Review by severo — APPROVED** [review]
OK, thanks for looking at the issue.

Feel free to merge once the conflicts are resolved

**Comment by AndreaFrancis** [comment]
>  delete the cached assets for HuggingFaceM4/WebSight to remove the empty images

I removed cached assets, and it looks to be working fine.
image

**Comment by lhoestq** [comment]
Cool thanks !

**Comment by albertvillanova** [comment]
Could it be possible that other datasets were also impacted besides "HuggingFaceM4/WebSight"?

Below, "cc_news" and even for /first-rows:
Screenshot from 2024-01-17 08-33-43

If so, we would have to delete their cached assets for all of them...

**Comment by severo** [comment]
maybe @AndreaFrancis knows of a way to look for all the /assets on s3 that have a size of 0 bytes?

**Comment by AndreaFrancis** [comment]
> maybe @AndreaFrancis knows of a way to look for all the /assets on s3 that have a size of 0 bytes?

Let me check. I think it is possible to use aws cli I will try.

**Pull request merged**
