### PR TITLE
remove redundant indices

### PR DESCRIPTION
**Pull request by geethika-123**
Removal of redundant indices from simple_cache.py.

### CODE REVIEW

**Comment by AndreaFrancis** [comment]
Thanks @geethika-123!  It looks good to me. You can pull the last change from main for the CI failed worker unit test.

**Comment by geethika-123** [comment]
Thank you @AndreaFrancis and @severo. I have retriggered the tests and they passed. Can you please merge this PR?

**Review by AndreaFrancis — APPROVED** [review]

**Comment by AndreaFrancis** [comment]
> I have retriggered the tests and they passed. Can you please merge this PR?


Sure! Thank you very much for your contribution!

**Comment by severo** [comment]
Changed in production. Thanks @geethika-123, well done!

**Pull request merged**
