### PR TITLE
Locally use volumes for workers code

### PR DESCRIPTION
**Pull request by lhoestq**
This way in a local dev env, one can restart a single worker container to apply their code changes instead of running `make stop` and `make start` again

### CODE REVIEW

**Review by severo — CHANGES_REQUESTED** [review]
Good idea!

The CI is failing because the e2e tests use the docker compose, and it doesn't work for some reason with this new setup.

**Comment by lhoestq** [comment]
I ended up defining a separate docker-compose file for dev.

This way the e2e tests can use the actual docker image that we may deploy.

I introduced
```bash
make dev-start
```

**Review by severo — APPROVED** [review]
OK, nice!

Two small comments:
- it's not DRY (but it's not really a problem, I just read https://gordonc.bearblog.dev/dry-most-over-rated-programming-principle/ :P)
- it's only to make it easier to dev on the worker. We could extend this to have a dev environment on the services too

**Comment by lhoestq** [comment]
Yea we'll just have to remember to update both when modifying something, but it should be fine since they're next to each other.

**Pull request merged**
