### PR TITLE
Update gradio

### LINKED ISSUE #2444: Upgrade Gradio to be able to copy/paste from dataframe cells
> Allow selecting texts in dataframe cells

was introduced in Gradio 4.17.0

https://github.com/gradio-app/gradio/blob/main/CHANGELOG.md

### PR DESCRIPTION
**Pull request by albertvillanova**
Update `gradio` to ^4.17.0.

Fix #2444.

### CODE REVIEW

**Review by severo — APPROVED** [review]
we could even upgrade to 4.18.0, no?

**Comment by albertvillanova** [comment]
Indeed it was updated to 4.18.0 (see the lock files):
- I set the required lower constraint on Gradio version for our needed feature (copy/paste from dataframe cells): ^4.17.0
- The I updated Gradio, and 4.18.0 was installed because it is the current version compatible with the version requirement:
> Caret requirements allow [SemVer](https://semver.org/) compatible updates to a specified version. An update is allowed if the new version number does not modify the left-most non-zero digit

**Comment by severo** [comment]
So precise, I love it

**Comment by albertvillanova** [comment]
I guess it is professional deformation... :sweat_smile: lol

**Pull request merged**
