### PR TITLE
Stop worker loop executor on SIGTERM

### LINKED ISSUE #1999: Better handling of k8s SIGTERM when stopping workers
We've observed recently that worker pods can take more than 1h to get killed by kubernetes (see internal [slack thread](https://huggingface.slack.com/archives/C04L6P8KNQ5/p1697641144036899) for example).
According to the k8s docs, at one point it sends a TERM and then after a grace period a SIGKILL on all the running processes.
If this keeps happening we need to improve the way we handle those to kill the pods faster.

One idea is to catch SIGTERM in the worker executor (main python process of workers) that would stop the worker loop (its subprocess where the actual code runs).

### PR DESCRIPTION
**Pull request by albertvillanova**
Fix #1999.

### CODE REVIEW

**Review by severo — APPROVED** [review]
I guess it's what we need (not a specialist).

Not sure if we really want it: do we want a test to be sure?

**Review by lhoestq — APPROVED** [review]
Awesome ! Would be cool to have a test indeed

**Comment by albertvillanova** [comment]
Yes, I agree we should test this. However I don't know how to send a SIGTERM within a test, without terminating the test itself...

Any hint?

**Comment by lhoestq** [comment]
Maybe run a subprocess from the test ?

**Comment by albertvillanova** [comment]
I am afraid I was not able to implement the test. I would suggest:
- either somebody else pushes the test to this PR
- or we merge it as it is and create an issue to implement the test in a subsequent PR

**Comment by severo** [comment]
I don't think I would be able to do it quickly either. Maybe @lhoestq. What do you think?

**Comment by lhoestq** [comment]
Let's merge it, we'll see if it works the next time we deploy anyway

**Pull request merged**
