### PR TITLE
invalidate the datasets cache after 3 years instead of 3 months

### PR DESCRIPTION
**Pull request by severo**
Quick fix to avoid deleting old cache entries (in particular, to be sure to keep the old dataset cache entries for datasets with a dataset script, now that we don't support scripts anymore)

### CODE REVIEW

**Comment by severo** [comment]
is it worth the time?

**Comment by lhoestq** [comment]
as you want ;)

**Comment by severo** [comment]
I'll open a "good first issue" issue for that

**Comment by severo** [comment]
https://github.com/huggingface/datasets-server/issues/2061

**Pull request merged**
