### PR TITLE
chore: update pypdf dependency in worker

### PR DESCRIPTION
**Pull request by AndreaFrancis**
Should fix https://github.com/huggingface/datasets-server/security/dependabot/200
But not sure where exactly we use this library, according to pypi page pypdf2 is now pypdf (Not sure if this will break something):
`NOTE: The PyPDF2 project is going back to its roots. PyPDF2==3.0.X will be the last version of PyPDF2. Development will continue with [pypdf==3.1.0](https://pypi.org/project/pyPdf/)`

### CODE REVIEW

**Comment by severo** [comment]
> not sure where exactly we use this

I installed it because some dataset script needed it.

**Comment by severo** [comment]
Here is the reference: https://github.com/huggingface/datasets-server/issues/688. So, after merging, let's refresh https://huggingface.co/datasets/jordyvl/unit-test_PDFfolder and ensure it still works

**Review by severo — APPROVED** [review]

**Comment by AndreaFrancis** [comment]
I see they use exactly `pypdf2` version and not `pypdf` https://huggingface.co/datasets/jordyvl/unit-test_PDFfolder/blob/main/unit-test_PDFfolder.py#L5 maybe this will not work, at least a commit is sent to their repo using `pypdf` instead right?

**Comment by severo** [comment]
I don't know. Maybe other @huggingface/datasets maintainers could chime in

**Comment by mariosasko** [comment]
The dataset in question uses `pdf2image` (does not depend on `pypdf`/`pypdf2`) for PDF decoding, so I think we can drop this dependency :).

**Review by severo — APPROVED** [review]

**Pull request merged**
