### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by severo**
This PR upgrades Starlette (vulnerability) (already done by #821 for front/ - this PR also fixes services/admin and services/api) 

It also upgrades all the dependencies to the next minor version. I checked the important ones: starlette, uvicorn.

And nearly all the changes come from the upgrade of mypy to v1 -> I fixed a lot of types, and it exposed some (not critical) bugs.

### CODE REVIEW

**Review by albertvillanova — APPROVED** [review]
Thanks.

OK, once conflicts with main resolved...

**Review by AndreaFrancis — APPROVED** [review]

**Comment by severo** [comment]
> OK, once conflicts with main resolved...

Done.

@lhoestq I fixed some details from #809, see:
- get mypy happy: https://github.com/huggingface/datasets-server/pull/823/commits/44531554ccc3b903acb32673dd8d68203c0db35a#diff-6636f2a4e026dc2652c3feed9369d0442a781b96a77cac10feab7e1f64d8d648R506
- add `from error` to get the complete traceback: https://github.com/huggingface/datasets-server/pull/823/commits/44531554ccc3b903acb32673dd8d68203c0db35a#diff-6636f2a4e026dc2652c3feed9369d0442a781b96a77cac10feab7e1f64d8d648R506 (it's redundant with the argument, we might be able to fix that in CustomError)
- I had to split your test function in two, because I don't know how to type it: https://github.com/huggingface/datasets-server/pull/823/commits/44531554ccc3b903acb32673dd8d68203c0db35a#diff-1690e9f8283cb9406a2585171e8f44dee147dbc7124d9bdff13520635cd83170R234. It's how I do it for the other tests everywhere, for that reason.

**Comment by severo** [comment]
Once merged, all the current PR will need a rebase (or a merge, but... I still think it's cleaner to rebase)

**Comment by severo** [comment]
Please don't hate me

**Pull request merged**
