### PR TITLE
Update datasets 2.14.3

### LINKED ISSUE #1589: Update datasets dependency to 2.14
TODO:
- [x] #1614 
- [x] #1616
- [x] #1617
- [x] #1619
- [x] #1620

### PR DESCRIPTION
**Pull request by albertvillanova**
Update `datasets` dependency to version 2.14.3, instead of 2.14.1 because there were issues. See:
- https://github.com/huggingface/datasets/pull/6094
- https://github.com/huggingface/datasets/pull/6095
- https://github.com/huggingface/datasets/pull/6105
- https://github.com/huggingface/datasets/pull/6107

We are merging this PR into a dedicated branch:
- https://github.com/huggingface/datasets-server/tree/update-datasets-2.14

This way we can merge subsequent required PRs into the same branch to fix the CI. Once the CI is green, we can merge the branch into main

Fix partially #1589.
Fix partially #1550.

Supersede and close #1577. 
Supersede and close #1588.

### CODE REVIEW

**Comment by albertvillanova** [comment]
Note that with 2.14.3 patch release (concretely, https://github.com/huggingface/datasets/pull/6107), we no longer have
```
TypeError: get_authentication_headers_for_url() got an unexpected keyword argument 'use_auth_token'
```

**Comment by albertvillanova** [comment]
I would suggest merging this PR into the branch:
- https://github.com/huggingface/datasets-server/tree/update-datasets-2.14

And then adding the fixes in separate PRs to that branch, until the CI is green in that branch.

Do you agree, @huggingface/datasets-server?

**Comment by severo** [comment]
yes, good methodology. this upgrade seems to be hard :)

**Comment by albertvillanova** [comment]
Yes, quite hard... Lots of different fixes are required... I prefer to do them separately, so that we can in the future refactor them individually and port them to `datasets` public API.

**Pull request merged**
