### PR TITLE
Update datasets dependency to 2.12.0 version

### LINKED ISSUE #1099: Upgrade datasets to 2.12.0
https://github.com/huggingface/datasets/releases/tag/2.12.0

### PR DESCRIPTION
**Pull request by albertvillanova**
After 2.12.0 datasets release, update dependencies on it.

Fix #1099.

### CODE REVIEW

**Comment by severo** [comment]
We have to upgrade in libcommon too (https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/pyproject.toml#L10). BTW, it might be the occasion to remove the explicit dependency from worker, since it depends on datasets through libcommon

**Comment by albertvillanova** [comment]
I didn't know about this change in the way we explicit dependencies... Before it was only set in worker. I am updating this PR...

**Comment by severo** [comment]
Yes, we need datasets for the `/rows` endpoint in services/api. Note that possibly we will move /rows to the workers, just with a highest priority, to get quick answers. So... possibly it will change again soon. Meanwhile, let's define it only in one place.

**Comment by albertvillanova** [comment]
The CI error on Build PR Documentation is unrelated: `504 Server Error: Gateway Time-out`.

The error in services/worker / unit-tests is weird: it should be an error because too long but gave a success. I also think it is unrelated: https://github.com/huggingface/datasets-server/actions/runs/4926280974/jobs/8801621665?pr=1147
```
FAILED tests/test_executor.py::test_executor_stops_on_long_job - AssertionError: must be an error because too long
assert <Status.SUCCESS: 'success'> == <Status.ERROR: 'error'>
  - error
  + success
```

**Comment by severo** [comment]
> The error in services/worker / unit-tests is weird: it should be an error because too long but gave a success. I also think it is unrelated: https://github.com/huggingface/datasets-server/actions/runs/4926280974/jobs/8801621665?pr=1147

Yes, it happens a lot of times. Relaunching generally fixes the test, but unit test that work 50% of the time is not very useful, we should find the issue and fix the test (in another issue).

**Comment by severo** [comment]
I created https://github.com/huggingface/datasets-server/issues/1156

**Comment by albertvillanova** [comment]
All CI tests are green now and the CI issues were unrelated to this PR. I think this can be approved.

**Comment by albertvillanova** [comment]
> Apart from the pure dependency upgrade, I think we still have to finish the tasks for the previous version upgrade to 2.11.0 (#1002). It can be in other PRs.
> 
> Also: are there similar tasks related to 2.12.0 release (https://github.com/huggingface/datasets/releases/tag/2.12.0). Maybe the dependency to beam?

Yes, indeed I am working on the list of tasks of the previous datasets release. I can work on the new one for this release as well.

**Pull request merged**
