### PR TITLE
Update hfh

### PR DESCRIPTION
**Pull request by severo**
In particular: we now use the new [`list_repo_refs`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.list_repo_refs) method, and the new [`revision`](https://github.com/huggingface/huggingface_hub/pull/1293) parameter when we create the `refs/convert/parquet` branch.

### CODE REVIEW

**Comment by Wauplin** [comment]
> Oh, for now, it's hard-coded to "main" (can be set to another value with an environment variable, but still: it's a constant)
> And it's not really useful to create the branch from main or from any other commit, since the first action is to delete all the contents, before adding the files we are interested in (parquet files).

Oh ok, makes sense. I thought you had a trick to know the initial commit.
If (or when?) it's ever possible, it would allow you to skip the "delete all" step before uploading parquet files. But that will be for later.

**Comment by severo** [comment]
Yes, that's what I mentioned in the commit message: https://github.com/huggingface/datasets-server/pull/700/commits/5364f81c908ad1af879ad7f3c8a44661adbe5235

> Maybe we will want to change this later once https://github.com/huggingface/huggingface_hub/issues/1288 is fixed.

**Comment by julien-c** [comment]
if you just want an empty tree (and not the initial commit of the repo), you can also create a commit completely detached from any branch (i think we discussed this in the other issue but i don't remember the discusion)

**Comment by Wauplin** [comment]
> you can also create a commit completely detached from any branch

Could be a solution but not implemented via the HTTP endpoint so far.
I'm also not sure it's a good idea as the `.gitattributes` file would be lost which is I think a very important one.

**Comment by julien-c** [comment]
(yes, but you could re-add a "standard" gitattributes quite easily in your commit i guess)

**Comment by julien-c** [comment]
(i do agree with you, this is just for the sake of discussion)

**Pull request merged**
