### PR TITLE
Update datasets to 2.9.0

### LINKED ISSUE #709: Update datasets to 2.9.0
After 2.9.0 `datasets` release, update dependencies on it.

### PR DESCRIPTION
**Pull request by albertvillanova**
Close #709.

### CODE REVIEW

**Comment by severo** [comment]
> [Lock poetry file](https://github.com/huggingface/datasets-server/pull/715/commits/30d5ce2fa7401534a8ab94356ed595bed67b21cc)

Nit: instead of running `poetry lock`, which has the side effect of updating all the dependencies, I run `poetry update datasets` after updating its version number.

**Review by severo — APPROVED** [review]
Nice! Thanks

**Comment by albertvillanova** [comment]
Thanks fir the tip, @severo, I take note! ;)

**Comment by severo** [comment]
feel free to merge

**Pull request merged**
