### PR TITLE
add filter column + ignore errors (fixes #2241)

### LINKED ISSUE #2241: The admin UI is not able to handle some gated datasets
See 
Capture d’écran 2024-01-08 à 13 47 41
Capture d’écran 2024-01-08 à 13 48 27

As I've not been accepted, I cannot see the status of the dataset in datasets-server.

I think that the admin UI should show a special value in the dataframe for the gated dataset that misses access, instead of hiding the result for all the datasets

### PR DESCRIPTION
**Pull request by severo**
fixes #2241

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]

**Comment by severo** [comment]
The admin UI has the filter column now

**Comment by severo** [comment]
I don't get why lmsys/lmsys-chat-1m has a red cross for filter if https://datasets-server.huggingface.co/is-valid?dataset=lmsys/lmsys-chat-1m

```json
{"preview":true,"viewer":true,"search":true,"filter":true}
```

**Comment by severo** [comment]
I think it's due to some responses not having 4 fields in the response... and we don't hardcode the number of columns or the name of the fields, so... maybe we're filling another row.

**Comment by severo** [comment]
Indeed, the second one: https://datasets-server.huggingface.co/is-valid?dataset=andersonbcdefg/synthetic_retrieval_tasks

has no filter field:

```json
{"preview":true,"viewer":true,"search":true}
```

**Comment by severo** [comment]
I don't want to spend too much time on the admin UI. @lhoestq feel free to look at it if you want (to hardcode the expected fields, maybe). I'll be looking at why some cache entries still miss the 'filter' field

**Comment by lhoestq** [comment]
ok !

**Comment by lhoestq** [comment]
It's a green cross now:

image

**Comment by severo** [comment]
yes because https://datasets-server.huggingface.co/is-valid?dataset=andersonbcdefg/synthetic_retrieval_tasks is fixed and has 4 fields now, not 3

**Comment by lhoestq** [comment]
I mean for lmsys/lmsys-chat-1m ;)

**Comment by severo** [comment]
> I mean for lmsys/lmsys-chat-1m ;)

I mean this too, and that's the bug: the red cross in lmsys/lmsys-chat-1m was a consequence of andersonbcdefg/synthetic_retrieval_tasks only having 3 fields. Because we fill the cells in order, not necessarily 4 cells per rows, we can introduce a shift (1 cell on one row, then 3 cells in the following one, which is completely incoherent)...

**Pull request merged**
