### PR TITLE
feat: 🎸 disable the viewer for org CyberHarem

### PR DESCRIPTION
**Pull request by severo**

### CODE REVIEW

**Comment by lhoestq** [comment]
Do we really want to block it ? We jut send them a message to ask the to add the NFAA tag so maybe let's just wait for their response first

**Comment by lhoestq** [comment]
Ah, just saw the slack thread - as you prefer

**Comment by severo** [comment]
What if we unblock them once they added the tag?

**Comment by severo** [comment]
slack thread (internal): https://huggingface.slack.com/archives/C042H6N5JR0/p1694159493341069

**Comment by lhoestq** [comment]
> What if we unblock them once they add the tag?

ok, I'll let you know

**Comment by giadilli** [comment]
Let's give the authors 48h to respond and then eventually we will disable the viewer. Thanks everyone

**Comment by lhoestq** [comment]
ok, reverting the block for now

**Pull request merged**
