### PR TITLE
add cron job to clean duckdb index cache

### PR DESCRIPTION
**Pull request by AndreaFrancis**
We have a cache folder in `/storage/duckdb-index`, this folder is used for cached downloads in `/search` and `/filter` while calling `  hf_hub_download` https://github.com/huggingface/datasets-server/blob/ef8a1cb34ba661b859962ac8d6c138374a0b0190/libs/libapi/src/libapi/duckdb.py#L78 (which needs a cache directory).
I noticed that we have old files in `/storage/duckdb-index/cache` which are using about 185G:
image

We can apply the same cleaning as we do for other folders so I added a new cron job.
I think another approach to avoid using `hf_hub_download` cache is to use `hf_transfer` directly, but I will investigate more about the advantages, meanwhile, the cron job will avoid increasing the storage usage.

### CODE REVIEW

**Comment by lhoestq** [comment]
The index files are the ones used by `/search` and `/filter` ? If so maybe it's fine to keep them longer on disk to not have to redownload them all the time and keep `/search` and `/filter` fast ?

**Comment by AndreaFrancis** [comment]
> The index files are the ones used by /search and /filter ? If so maybe it's fine to keep them longer on disk to not have to redownload them all the time and keep /search and /filter fast ?

Yes but, it is like we have a copy of the files first in the cache (This is the way hf_hub_download works) and then, we move the file to /storage/duckdb-index/downloads so, maybe I can enable local_dir_use_symlinks=True https://huggingface.co/docs/huggingface_hub/package_reference/file_download#huggingface_hub.hf_hub_download.local_dir_use_symlinks and configure a long expiration time for the folder (like 3 days same as /downloads https://github.com/huggingface/datasets-server/blob/main/chart/env/prod.yaml#L221)

**Review by severo — APPROVED** [review]
OK! The only thing to decide is how long we should keep the files (@lhoestq mentioned having them for more than. 3 hours)

**Comment by AndreaFrancis** [comment]
> OK! The only thing to decide is how long we should keep the files (@lhoestq mentioned having them for more than. 3 hours)

I changed it to 3 days for now, let's see how it goes and we can set it a new value later.

**Pull request merged**
