### PR TITLE
fix: chart dependencies

### PR DESCRIPTION
**Pull request by rtrompier**

### CODE REVIEW

**Review by AndreaFrancis — APPROVED** [review]
Thanks!

**Comment by severo** [comment]
Why are we versioning the dependencies? Shouldn't they be obtained from their repositories instead?

**Comment by rtrompier** [comment]
We choose to push charts into the repository, because Bitnami regularly remove old versions. If we don't want be blocked by a technical migration, we have to commit these files.

**Comment by severo** [comment]
OK, thanks

**Pull request merged**
