### PR TITLE
Add blockedDatasets variable

### PR DESCRIPTION
**Pull request by lhoestq**
and block `alexandrainst/nota`, see [internal slack thread](https://huggingface.slack.com/archives/C04L6P8KNQ5/p1693548446825959)

The idea is to never process anything for blocked datasets. I also chose to not store anything in the cache in this case

### CODE REVIEW

**Review by severo — COMMENTED** [review]
Should we also delete existing cache entries? Maybe in a cronjob, or in a migration every time the block list has changed?

Also: should we remove the other block list (only used in config-parquet-and-info) ?

**Comment by lhoestq** [comment]
I think the cache entries should be deleted yes, but not a big deal for now given that there is only one dataset.

> Also: should we remove the other block list (only used in config-parquet-and-info) ?

let's keep it for now, but ideally yes we should remove it imo

**Comment by severo** [comment]
OK, created two issues: #1753 #1754

**Comment by lhoestq** [comment]
Thanks ! May I merge this one ? I'd like to deploy after this one

**Comment by severo** [comment]
yes, sorry!

**Pull request merged**
