### PR TITLE
Rename classes to indicate inheritance

### PR DESCRIPTION
**Pull request by geethika-123**
This commit adds `Document` suffix to classes to indicate inheritance.

cc @severo 

Fixes https://github.com/huggingface/datasets-server/issues/1359

### CODE REVIEW

**Comment by severo** [comment]
Thanks for the PR. As the quality checks show, the refactoring is still missing in some other parts of the code.

Also, a rebase (or merge) is needed to keep synchronized with the main branch.

Please tell us if you need a hand with some of these points. I am looking forward to this PR being merged into the datasets server!

**Comment by geethika-123** [comment]
@severo - Thanks for the help. I ran `make quality` and `make style` in all the jobs, services and worker folders. Previously I ran it from jobs and services alone. Please take a look and let me know I need to run other tests. I'm trying to run e2es locally on my intel MacBook air however the docker builds are running forever.

**Comment by severo** [comment]
Thanks! I'll look at it later today. Yes, the docker builds are very long, in particular the first time.

**Comment by severo** [comment]
I think the issue in the CI is due to the "spawning" secret that cannot be used because the original branch is not from this repo. Could you confirm @AndreaFrancis ?

**Review by severo — APPROVED** [review]
Perfect contribution, well done @geethika-123!

**Comment by geethika-123** [comment]
Thank you @severo for guidance all along.

**Pull request merged**
