### PR TITLE
Re-lower row group

### PR DESCRIPTION
**Pull request by lhoestq**
Re-add the changes from https://github.com/huggingface/datasets-server/pull/833 that were inadvertently removed by https://github.com/huggingface/datasets-server/pull/985

close https://github.com/huggingface/datasets-server/issues/1127

### CODE REVIEW

**Review by severo — APPROVED** [review]
Thanks!

One question: should we include bytes too? I have the feeling that it's another case where the calls to /rows would be slow if we have big rowgroups

**Comment by lhoestq** [comment]
I got a bunch of BadRequestError in the CI - is it OK to merge anyway ? Or is there anything I need to do to fix them ?

**Comment by severo** [comment]
Seems like an issue with the LFS on Hub CI

**Comment by severo** [comment]
> We have the bytes from the preview computation no ?

I didn't understand

**Comment by lhoestq** [comment]
Sorry I misunderstood. I thought you were mentioning the actual number of bytes per row.

But you meant the "binary" type right ? I agree we should also include it - let me add it real quick

**Review by severo — APPROVED** [review]

**Pull request merged**
