### PR TITLE
Publish /healthcheck again

### PR DESCRIPTION
**Pull request by severo**
<strike>It is needed by argocd</strike>

Capture d’écran 2023-03-02 à 13 22 09

It is needed by the ALB

It's defined at https://github.com/huggingface/datasets-server/blob/fb48ed36cd41b13fba88b6b18072faf1bbd1fb62/chart/env/prod.yaml#L125

### CODE REVIEW

**Review by rtrompier — COMMENTED** [review]
What is the response code for the health-check endpoint ? I don't see the code in this PR.

**Comment by severo** [comment]
The healthcheck is served by the API service

**Comment by XciD** [comment]
> It is needed by argocd
> 
> Capture d’écran 2023-03-02 à 13 22 09
> 
> It's defined at
> 
> https://github.com/huggingface/datasets-server/blob/fb48ed36cd41b13fba88b6b18072faf1bbd1fb62/chart/env/prod.yaml#L125

Will not solved argo health issue, but ALB.
For argo, sounds like you have some pod that dont schedule (Pending), you may have to lower your request cpu

**Review by XciD — APPROVED** [review]

**Comment by severo** [comment]
Oh, right, I was confused.

**Comment by severo** [comment]
Capture d’écran 2023-03-02 à 13 49 19

**Pull request merged**
