### PR TITLE
fix ogg audio

### PR DESCRIPTION
**Pull request by AndreaFrancis**
Fix for https://github.com/huggingface/datasets-server/issues/2045

### CODE REVIEW

**Comment by severo** [comment]
maybe add a test to ensure that ogg files were not working before, and are working now?

**Comment by AndreaFrancis** [comment]
> maybe add a test to ensure that ogg files were not working before, and are working now?

I added a specific test. It was needed to mock s3 bucket since the issue only appears when using fsspec+s3fs.
Note that I had to do a couple of patches because of aiobotocore https://github.com/getmoto/moto/issues/6836 and https://github.com/aio-libs/aiobotocore/issues/755
`
MockRawResponse' object has no attribute 'raw_headers' error when using moto with s3fs
`

**Review by severo — APPROVED** [review]

**Comment by severo** [comment]
wow, it was more complex than expected. Maybe another review before merging?

**Comment by AndreaFrancis** [comment]
> wow, it was more complex than expected. Maybe another review before merging?

Sure.
I will fix the import error in libcommon unittests:
```
ImportError while importing test module '/home/runner/work/datasets-server/datasets-server/libs/libcommon/tests/viewer_utils/test_features.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/viewer_utils/test_features.py:12: in <module>
    import boto3
E   ModuleNotFoundError: No module named 'boto3'
```

**Review by severo — APPROVED** [review]

**Pull request merged**
