### PR TITLE
Fix CI mypy error: "WorkerFactory" has no attribute "app_config"

### PR DESCRIPTION
**Pull request by albertvillanova**
Fix type checking on WorkerLoop.loop method, when tryin to access the worker_factory's attribute app_config.

This PR fixes an issue introduced by:
- #774

```
src/datasets_based/worker_loop.py:100: error: "WorkerFactory" has no attribute "app_config"
```

### CODE REVIEW

**Comment by albertvillanova** [comment]
The root error raised by mypy is that `WorkerLoop.loop()` is trying to get the attribute `self.worker_factory.app_config` on an instance of `WorkerFactory`, whereas the attribute `app_config` is defined only for its child `DatasetBasedWorkerFactory(WorkerFactory)`.

**Comment by albertvillanova** [comment]
Another approach would be to define the attribute `app_config` in the interface `WorkerFactory`...

**Comment by severo** [comment]
The bug has been introduced by:

https://github.com/huggingface/datasets-server/pull/774/files#diff-4326852d55eab85b019c702a4579f696cb429aaf13586d8e3a1824581f8c9e34R100

@lhoestq I would vote to remove this log or move it elsewhere because we will soon implement https://github.com/huggingface/datasets-server/issues/737, which will allow a worker loop to manage various endpoints.

**Comment by albertvillanova** [comment]
I am making the corresponding changes and you review them.

**Review by lhoestq — APPROVED** [review]
thanks - it's fine to remove it

**Review by severo — APPROVED** [review]
Thanks!!

**Comment by severo** [comment]
(I'm merging to fix the CI on other PRs)

**Pull request merged**
