### PR TITLE
Make workers' errors derive from WorkerError

### PR DESCRIPTION
**Pull request by albertvillanova**
Make workers' errors derive from `WorkerError`, instead of parent `CustomError`.

### CODE REVIEW

**Review by severo — APPROVED** [review]
Thanks! It was incoherent

**Comment by albertvillanova** [comment]
Apparently there is (again) a connectivity issue with http://azure.archive.ubuntu.com mirrors...
I will relaunch the CI failed jobs later.

**Comment by severo** [comment]
OK, Azure seems to work again. And there is an issue with the types: the signatures are not exactly the same

**Comment by albertvillanova** [comment]
@severo, I have created `GeneralWorkerError(WorkerError)` and make errors in worker.py derive from it, while all workers' error continue to derive from `WorkerError`.

Alternatively I could have renamed `WorkerError` to `BaseWorkerError`, create new make errors `WorkerError(BaseWorkerError)` and make errors in worker.py derive from it, while all workers' error now derive from `BaseWorkerError`.

What do you think is better?

**Comment by albertvillanova** [comment]
The CI error is unrelated to this PR: https://github.com/huggingface/datasets-server/actions/runs/4105164627/jobs/7081642597
```
src/datasets_based/worker_loop.py:100: error: "WorkerFactory" has no attribute "app_config"
```

See:
- #778

**Comment by severo** [comment]
I think it's ok, now

**Pull request merged**
