### PR TITLE
Adding EFS volumes for cache, parquet and duckdb storage

### PR DESCRIPTION
**Pull request by AndreaFrancis**
Related to https://github.com/huggingface/datasets-server/issues/1407
Adding new volumes for: cache (datasets library), parquet and duckdb
Based on https://github.com/huggingface/infra/pull/607, the persistenceVolumeClaims should be:

- datasets-server-cache-pvc
- datasets-server-parquet-pvc
- datasets-server-duckdb-pvc

I think it depends on https://github.com/huggingface/infra/pull/607/files to be merged/implemented first.

### CODE REVIEW

**Comment by AndreaFrancis** [comment]
@rtrompier regarding datasets-server migration to EFS usage, not quite sure if the changes in this PR are enough, could you advice?

**Comment by severo** [comment]
Nice. I'll let @rtrompier chime in, as it's really infra related. I think it would be good to test on staging before prod. Do we have dedicated EFS for staging?

**Review by rtrompier — APPROVED** [review]
LGTM but I have to create the `datasets-server-duckdb-pvc` before.

**Comment by rtrompier** [comment]
> Nice. I'll let @rtrompier chime in, as it's really infra related. I think it would be good to test on staging before prod. Do we have dedicated EFS for staging?

Yes we have EFS for staging env as well. I will create volume tomorrow for both environment.

**Pull request merged**
