### PR TITLE
adapt JWT verification to new field

### PR DESCRIPTION
**Pull request by severo**
The JWT now contains `permissions: {"repo.content.read": true}` instead
of the (soon deprecated) ``read: true`.

fixes https://github.com/huggingface/datasets-server/issues/2620.

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
Note that technically those also work for us:

- `{"repo.content.write": true}`
- `{"repo.write": true}`
- `{"repo.read": true}`

We'll probably leave "repo.content.read" to be predictable, but if you want to 100% future-proof, you can check any of those is `true`

**Comment by coyotte508** [comment]
> OK. Good to know. Is there a specific algorithm to use to check these different permissions? Or just check that any of them is `true` (which is what I did in [the last commit](https://github.com/huggingface/datasets-server/pull/2622/commits/53f8e87663e237fb8823f21e33e7f86c714bd25e))?

it's like webhooks, basically

write=true => gives access to read
higher scopes gives access to lower scope ("repo". gives access to "repo.content")

**Comment by severo** [comment]
and should we raise here?

https://github.com/huggingface/datasets-server/pull/2622/files#diff-9fdf2c5e5d43723757c70f9c7143257d2990b894107400e957918d30b2692462R334

when the permissions are: `{"repo.write": True, "repo.content.read": False}`

**Comment by coyotte508** [comment]
it works with an "allow" rather than "block" principle, so `{"repo.content.read:" false, "repo.content.write": true}` is valid

**Review by AndreaFrancis — APPROVED** [review]

**Pull request merged**
